/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CeleratePanel.java
 *
 * Created on Apr 17, 2011, 5:07:31 PM
 */
package com.localization.application;

import com.localization.manager.LocationDataManagement;
import com.localization.other.TreeDataManagement;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class SelectTestLocationPanel extends javax.swing.JPanel {

    private static JDialog parentDialog;
    private ArrayList<LocationDataObject> allRootLocation;
    private final LocationDataObject treeRootLocation;
    private static SelectTestLocationPanel singleton;
    private static String treeRootId = "0";
    private JDialog datatypeDialog;

    SelectTestLocationPanel(LocationDataObject treeRootLocation) {
        this.treeRootLocation = treeRootLocation;
        initComponents();
        intiOtherComponents();
    }

    public static SelectTestLocationPanel createInstance(JDialog dialog, LocationDataObject treeRootLocation) {
        parentDialog = dialog;
        
        if (!treeRootId.equals(treeRootLocation.getLocationId())) {
            treeRootId = treeRootLocation.getLocationId();
            singleton = new SelectTestLocationPanel(treeRootLocation);
        }
        
        return singleton;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTreeContainer = new javax.swing.JScrollPane();
        treeLocation = new javax.swing.JTree();
        OKjButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        panelTreeContainer.setViewportView(treeLocation);

        OKjButton.setText("OK");
        OKjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKjButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTreeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(OKjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(canceljButton)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTreeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKjButton)
                    .addComponent(canceljButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        this.parentDialog.dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    private void OKjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKjButtonActionPerformed
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeLocation.getLastSelectedPathComponent();
        LocalizationClient.selectTestLocation = (LocationDataObject) node.getUserObject();
//        LocalizationClient.testLocationRootjLabel.setText(LocalizationClient.selectTestLocation.getParentLocation().getLocationName());
        LocalizationClient.testLocationRootjLabel.setText("lau 7");
        LocalizationClient.testLocationNamejLabel.setText(LocalizationClient.selectTestLocation.getLocationName());
//        LocalizationClient.testLocationUserjLabel.setText(LocalizationClient.selectTestLocation.getUser().getUserName());
        LocalizationClient.testLocationUserjLabel.setText("nhu");
        this.parentDialog.dispose();
    }//GEN-LAST:event_OKjButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKjButton;
    private javax.swing.JButton canceljButton;
    private javax.swing.JScrollPane panelTreeContainer;
    private javax.swing.JTree treeLocation;
    // End of variables declaration//GEN-END:variables

    private void intiOtherComponents() {
        reloadTreeView();
    }

    public void reloadTreeView() {
        if (this.treeRootLocation != null) {
            this.treeLocation = new JTree(TreeDataManagement.createLocationTreeStructure(treeRootLocation));
        } else {
            this.allRootLocation = LocationDataManagement.getAllRootLocation();
            this.treeLocation = new JTree(TreeDataManagement.createListLocationTreeStructure(this.allRootLocation));
        }
        treeLocation.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        this.treeLocation.setVisible(true);
        this.panelTreeContainer.setViewportView(this.treeLocation);

        this.updateView();
    }

    /**
     * update view
     */
    public void updateView() {
        this.updateUI();
        this.invalidate();
    }
}
