/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataManagementPanel.java
 *
 * Created on Feb 20, 2011, 7:37:25 PM
 */
package com.localization.application;

import com.localization.datatype.panel.DataTypeAbstractPanel;
import com.localization.other.ApplicationConfiguration;
import javax.swing.JDialog;
import localization.data.entity.contentobject.DataTypeDataObject;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class StartCaliratePanel extends javax.swing.JPanel {

    private JDialog parentDialog;
    private CaliratePanel parentPanel;
    private DataTypeDataObject datatype;
    private String datatypeClassPath;
    private static LocationDataObject selectedLocation;
    private static LocationDataObject treeRootLocation;

    public static LocationDataObject getTreeRootLocation() {
        return treeRootLocation;
    }

    public static LocationDataObject getSelectedLocation() {
        return selectedLocation;
    }

    /** Creates new form DataManagementPanel */
    public StartCaliratePanel(JDialog parentDialog, LocationDataObject selectedLocationParam) {
        this.parentDialog = parentDialog;
        selectedLocation = selectedLocationParam;
        initComponents();
        initOtherComponents();
    }

    StartCaliratePanel(JDialog parentDialog, CaliratePanel parentPanel, LocationDataObject locationDataObject) {
        this.parentDialog = parentDialog;
        this.parentPanel = parentPanel;
        selectedLocation = locationDataObject;

        initComponents();
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelDataType = new javax.swing.JLabel();
        panelScrollContainer = new javax.swing.JScrollPane();
        panelContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelLocationName = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        saveJButton = new javax.swing.JButton();
        canceljButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Collect Data For Calibration");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Data Type:");

        panelContainer.setLayout(new javax.swing.BoxLayout(panelContainer, javax.swing.BoxLayout.PAGE_AXIS));
        panelScrollContainer.setViewportView(panelContainer);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Location:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("User:");

        saveJButton.setText("Save");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        canceljButton.setText("Cancel");
        canceljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceljButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(labelLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataType, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
            .addComponent(panelScrollContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(saveJButton)
                .addGap(18, 18, 18)
                .addComponent(canceljButton)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(labelLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(labelDataType, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(panelScrollContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveJButton)
                    .addComponent(canceljButton))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        //will add the selected location to list added location
        this.parentPanel.addNewLocation();
        this.parentDialog.dispose();
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void canceljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceljButtonActionPerformed
        this.parentDialog.dispose();
    }//GEN-LAST:event_canceljButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceljButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelDataType;
    private javax.swing.JLabel labelLocationName;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JScrollPane panelScrollContainer;
    private javax.swing.JButton saveJButton;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponents() {
        LocationDataObject rootLocationDataObject = selectedLocation;

        while (rootLocationDataObject.getParentLocation() != null) {
            rootLocationDataObject = rootLocationDataObject.getParentLocation();
            System.out.println(rootLocationDataObject.getLocationId());
        }

        if (rootLocationDataObject == null) {
            parentDialog.dispose();
        } else {
            try {
                treeRootLocation = rootLocationDataObject;
                datatype = rootLocationDataObject.getAlgorithm().getDataType();
                System.out.println(datatype.getDataTypeClassName());
                labelDataType.setText(datatype.getDataTypeName());
                labelLocationName.setText(selectedLocation.getLocationName());
                labelUserName.setText(selectedLocation.getUser().getUserName());
                datatypeClassPath = ApplicationConfiguration.load().datatypepanelPackage + "." + datatype.getDataTypeName() + "Panel";
                Class dataTypePanelClass = Class.forName(datatypeClassPath);
                DataTypeAbstractPanel datatypePanel = (DataTypeAbstractPanel) dataTypePanelClass.getConstructor(null).newInstance(null);
                datatypePanel.initPanel(this.parentDialog);
                datatypePanel.setVisible(true);
                panelContainer.add(datatypePanel);
                this.updateView();
            } catch (Exception ex) {
                System.out.println("Problem for loading class.");
                parentDialog.dispose();
            }

        }
    }

    private void updateView() {
        panelContainer.updateUI();
        panelContainer.invalidate();
        panelScrollContainer.updateUI();
        panelScrollContainer.invalidate();
        this.updateUI();
        this.invalidate();
    }
}
