/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocalizationMain.java
 *
 * Created on Dec 4, 2010, 10:31:56 AM
 */
package com.localization.application;

import com.localization.application.panel.LocationManagementPanel;
import com.localization.application.panel.forframe.CreateAlgorithmPanel;
import com.localization.application.panel.forframe.CreateDataTypePanel;
import com.localization.application.panel.forframe.CreateLocationPanelWithSize;
import com.localization.application.panel.forframe.CreateUserPanel;
import com.localization.application.panel.forframe.LoginPanel;
import com.localization.application.panel.forframe.PreferencesPanel;
import com.localization.other.ApplicationConfiguration;
import javax.swing.JDialog;
import localization.data.entity.contentobject.UserDataObject;

/**
 *
 * @author leobin
 */
public class LocalizationMain extends javax.swing.JFrame {

    /** Creates new form LocalizationMain */
    public LocalizationMain() {
        initComponents();
        //added by leobin
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        browseAlgorithmPanel1 = new com.localization.application.panel.BrowseAlgorithmPanel();
        browseDataTypePanel1 = new com.localization.application.panel.BrowseDataTypePanel();
        browseLocationPanel1 = new com.localization.application.panel.BrowseLocationPanel();
        browseUserPanel1 = new com.localization.application.panel.BrowseUserPanel();
        welcomePanel1 = new com.localization.application.panel.WelcomePanel();
        locationManagementPanel1 = new com.localization.application.panel.LocationManagementPanel();
        menuBar = new javax.swing.JMenuBar();
        menuGeneral = new javax.swing.JMenu();
        menuItemPreference = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuLocation = new javax.swing.JMenu();
        menuItemBrowseLocation = new javax.swing.JMenuItem();
        menuItemCreateLocation = new javax.swing.JMenuItem();
        menuOther = new javax.swing.JMenu();
        menuItemCreateUser = new javax.swing.JMenuItem();
        menuItemUserManagement = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemCreateAlgorithm = new javax.swing.JMenuItem();
        menuItemAlgorithmManagement = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemCreateDataType = new javax.swing.JMenuItem();
        menuItemDataManagemet = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        panelMain.setLayout(new java.awt.CardLayout());
        panelMain.add(browseAlgorithmPanel1, "browse-algorithm");
        panelMain.add(browseDataTypePanel1, "browse-datatype");
        panelMain.add(browseLocationPanel1, "browse-location");
        panelMain.add(browseUserPanel1, "browse-user");
        panelMain.add(welcomePanel1, "card6");
        panelMain.add(locationManagementPanel1, "manage-location");

        menuGeneral.setText("General"); // NOI18N

        menuItemPreference.setText("Preferences"); // NOI18N
        menuItemPreference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPreferenceActionPerformed(evt);
            }
        });
        menuGeneral.add(menuItemPreference);

        menuItemExit.setText("Exit"); // NOI18N
        menuGeneral.add(menuItemExit);

        menuBar.add(menuGeneral);

        menuLocation.setText("Location"); // NOI18N

        menuItemBrowseLocation.setText("Browse"); // NOI18N
        menuItemBrowseLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBrowseLocationActionPerformed(evt);
            }
        });
        menuLocation.add(menuItemBrowseLocation);

        menuItemCreateLocation.setText("Create"); // NOI18N
        menuItemCreateLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateLocationActionPerformed(evt);
            }
        });
        menuLocation.add(menuItemCreateLocation);

        menuBar.add(menuLocation);

        menuOther.setText("User");

        menuItemCreateUser.setText("Create User");
        menuItemCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateUserActionPerformed(evt);
            }
        });
        menuOther.add(menuItemCreateUser);

        menuItemUserManagement.setText("User Management");
        menuItemUserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUserManagementActionPerformed(evt);
            }
        });
        menuOther.add(menuItemUserManagement);

        menuBar.add(menuOther);

        jMenu1.setText("Algorithm");

        menuItemCreateAlgorithm.setText("Create Algorithm");
        menuItemCreateAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateAlgorithmActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemCreateAlgorithm);

        menuItemAlgorithmManagement.setText("Algorithm Management");
        menuItemAlgorithmManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlgorithmManagementActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAlgorithmManagement);

        menuBar.add(jMenu1);

        jMenu2.setText("DataType");

        menuItemCreateDataType.setText("Create DataType");
        menuItemCreateDataType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateDataTypeActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCreateDataType);

        menuItemDataManagemet.setText("Data Type Management");
        menuItemDataManagemet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDataManagemetActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemDataManagemet);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCreateLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateLocationActionPerformed
        JDialog dialog = new JDialog(this, true);
        CreateLocationPanelWithSize panel = new CreateLocationPanelWithSize(dialog, this.panelMain);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemCreateLocationActionPerformed

    private void menuItemBrowseLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBrowseLocationActionPerformed
        CardLayoutHandlerFunction.changeCardView(PANEL_BROWSE_LOCATION);
    }//GEN-LAST:event_menuItemBrowseLocationActionPerformed

    private void menuItemPreferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPreferenceActionPerformed
        // Create new dialog for edit configuration
        JDialog dialog = new JDialog(this, true);
        PreferencesPanel panel = new PreferencesPanel(dialog, this.panelMain);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemPreferenceActionPerformed

    private void menuItemUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUserManagementActionPerformed
        CardLayoutHandlerFunction.changeCardView(PANEL_BROWSE_USER);
    }//GEN-LAST:event_menuItemUserManagementActionPerformed

    private void menuItemAlgorithmManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlgorithmManagementActionPerformed
        CardLayoutHandlerFunction.changeCardView(PANEL_BROWSE_ALGORITHM);
    }//GEN-LAST:event_menuItemAlgorithmManagementActionPerformed

    private void menuItemDataManagemetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDataManagemetActionPerformed
        CardLayoutHandlerFunction.changeCardView(PANEL_BROWSE_DATATYPE);
    }//GEN-LAST:event_menuItemDataManagemetActionPerformed

    private void menuItemCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateUserActionPerformed
        JDialog dialog = new JDialog(this, true);
        CreateUserPanel panel = new CreateUserPanel(dialog, null);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemCreateUserActionPerformed

    private void menuItemCreateAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateAlgorithmActionPerformed
        JDialog dialog = new JDialog(this, true);
        CreateAlgorithmPanel panel = new CreateAlgorithmPanel(dialog, null);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemCreateAlgorithmActionPerformed

    private void menuItemCreateDataTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateDataTypeActionPerformed
        JDialog dialog = new JDialog(this, true);
        CreateDataTypePanel panel = new CreateDataTypePanel(dialog, null);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemCreateDataTypeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            LocationManagementPanel.datatypeDialog.dispose();
            ApplicationConfiguration.load().saveConfiguration();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        try {
            LocationManagementPanel.datatypeDialog.setEnabled(!LocationManagementPanel.datatypeDialog.isFocused());
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            LocationManagementPanel.datatypeDialog.setEnabled(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                LocalizationMain localizationMain = new LocalizationMain();
                localizationMain.setVisible(true);

                localizationMain.callLogin();
                LocalizationMain.localizationMain = localizationMain;
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.localization.application.panel.BrowseAlgorithmPanel browseAlgorithmPanel1;
    private com.localization.application.panel.BrowseDataTypePanel browseDataTypePanel1;
    private com.localization.application.panel.BrowseLocationPanel browseLocationPanel1;
    private com.localization.application.panel.BrowseUserPanel browseUserPanel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private com.localization.application.panel.LocationManagementPanel locationManagementPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGeneral;
    private javax.swing.JMenuItem menuItemAlgorithmManagement;
    private javax.swing.JMenuItem menuItemBrowseLocation;
    private javax.swing.JMenuItem menuItemCreateAlgorithm;
    private javax.swing.JMenuItem menuItemCreateDataType;
    private javax.swing.JMenuItem menuItemCreateLocation;
    private javax.swing.JMenuItem menuItemCreateUser;
    private javax.swing.JMenuItem menuItemDataManagemet;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemPreference;
    private javax.swing.JMenuItem menuItemUserManagement;
    private javax.swing.JMenu menuLocation;
    private javax.swing.JMenu menuOther;
    private javax.swing.JPanel panelMain;
    private com.localization.application.panel.WelcomePanel welcomePanel1;
    // End of variables declaration//GEN-END:variables
    public static final String PANEL_BROWSE_LOCATION = "browse-location";
    public static final String PANEL_LOCATION_MANAGEMENT = "manage-location";
    public static final String PANEL_BROWSE_USER = "browse-user";
    public static final String PANEL_BROWSE_ALGORITHM = "browse-algorithm";
    public static final String PANEL_BROWSE_DATATYPE = "browse-datatype";
    public static LocalizationMain localizationMain;
    public static UserDataObject loginUser = null;

    /**
     * added by leobin
     * init components which is manual added
     */
    private void initOtherComponents() {
        //created by leobin, usingn cardlayout
        CardLayoutHandlerFunction.setPanelMain(panelMain);
//        CardLayout cardLayout = new CardLayout();
//        panelMain.add(cardLayout);
//        cardLayout.add(createEventPanel, PANEL_CREATE_EVENT);
//
//        cardLayout.setVisible(true);
//        cardLayout.show(panelMain, PANEL_CREATE_EVENT);

        //show login panel

    }

    public void callLogin() {
        JDialog dialog = new JDialog(this, true);
        LoginPanel panel = new LoginPanel(dialog, this);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }

    public void callUpdateForLayout(String cardname) {
    }
}
