/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataTypeAbstractPanel.java
 *
 * Created on Feb 20, 2011, 8:04:44 PM
 */

package com.localization.datatype.panel;

import javax.swing.JDialog;

/**
 *
 * @author leobin
 */
public class DataTypeAbstractPanel extends javax.swing.JPanel {

    protected JDialog parentDialog;
    /** Creates new form DataTypeAbstractPanel */
    public DataTypeAbstractPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Need to call parent when extend.
     * @param parentDialog
     */
    public void initPanel(JDialog parentDialog){
        this.parentDialog = parentDialog;
    }

}
