/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BrowseLocationPanel.java
 *
 * Created on Dec 4, 2010, 11:43:19 PM
 */
package com.localization.application.panel;

import com.localization.application.LocalizationMain;
import com.localization.application.panel.item.LocationPanel;
import com.localization.manager.LocationDataManagement;
import localization.data.entity.contentobject.LocationDataObject;

import java.util.ArrayList;

/**
 *
 * @author leobin
 */
public class BrowseLocationPanel extends LocalizationPanel {

    /** Creates new form BrowseLocationPanel */
    public BrowseLocationPanel() {
        initComponents();
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                panelListLocation = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();

                panelListLocation.setLayout(new javax.swing.BoxLayout(panelListLocation, javax.swing.BoxLayout.PAGE_AXIS));
                jScrollPane1.setViewportView(panelListLocation);

                jLabel1.setText("Browse Location");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jLabel1)
                                .addContainerGap(249, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

    @Override
    public void reload() {
        ArrayList<LocationDataObject> allRootLocation = LocationDataManagement.getAllRootLocationByUserID(LocalizationMain.loginUser.getUserId());
        //List<LocationDataObject> allRootLocation = LocalizationMain.loginUser.getLocations();
        System.out.println(panelListLocation.getComponents().length);
        System.out.println(allRootLocation.size());
        if (panelListLocation.getComponents().length < allRootLocation.size()) {
            for (int j = panelListLocation.getComponents().length; j < allRootLocation.size(); j++) {
                LocationDataObject location = allRootLocation.get(j);
                LocationPanel locationPanel = new LocationPanel(location);
                locationPanel.setVisible(true);
                panelListLocation.add(locationPanel);
            }
        } else {
            if (panelListLocation.getComponents().length > allRootLocation.size()){
                for (int j = 0 ; j < panelListLocation.getComponents().length;j++){
                    LocationPanel locationPanel = (LocationPanel) panelListLocation.getComponent(j);
                    if (locationPanel.isRemove){
                        panelListLocation.remove(j);
                    }
                }
            }
        }
        updateView();
    }

    /**
     * init other components
     */
    private void initOtherComponents() {
        try {
            ArrayList<LocationDataObject> allRootLocation = LocationDataManagement.getAllRootLocationByUserID(LocalizationMain.loginUser.getUserId());

            for (int i = 0; i < allRootLocation.size(); i++) {
                LocationDataObject location = allRootLocation.get(i);
                LocationPanel locationPanel = new LocationPanel(location);
                locationPanel.setVisible(true);
                panelListLocation.add(locationPanel);
            }
            updateView();
        } catch (Exception e) {
            System.out.println("Problem in loading init browse location form");
        }
    }
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JPanel panelListLocation;
        // End of variables declaration//GEN-END:variables

    private void updateView() {
        panelListLocation.invalidate();
        panelListLocation.updateUI();
    }
}
