/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BrowseUserPanel.java
 *
 * Created on Feb 12, 2011, 2:11:45 PM
 */
package com.localization.application.panel;

import com.localization.application.LocalizationMain;
import com.localization.application.panel.item.LocationPanel;
import com.localization.application.panel.item.UserPanel;
import com.localization.manager.LocationDataManagement;
import com.localization.manager.UserDataManagement;
import java.util.ArrayList;
import localization.data.entity.contentobject.LocationDataObject;
import localization.data.entity.contentobject.UserDataObject;

/**
 *
 * @author leobint
 */
public class BrowseUserPanel extends LocalizationPanel {

    /** Creates new form BrowseUserPanel */
    public BrowseUserPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelListUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        panelListUser.setLayout(new javax.swing.BoxLayout(panelListUser, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(panelListUser);

        jLabel1.setText("Browse User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListUser;
    // End of variables declaration//GEN-END:variables
    public static boolean isEdited = false;

    @Override
    public void reload() {
        ArrayList<UserDataObject> allUser = UserDataManagement.getAllUserByUserType(UserDataObject.USER_TYPE_ALL);
        System.out.println(panelListUser.getComponents().length);
        System.out.println(allUser.size());
        if (panelListUser.getComponents().length < allUser.size()) {
            for (int j = panelListUser.getComponents().length; j < allUser.size(); j++) {
                UserDataObject user = allUser.get(j);
                UserPanel userPanel = new UserPanel(user);
                userPanel.setVisible(true);
                panelListUser.add(userPanel);
            }
        } else {
            if (panelListUser.getComponents().length > allUser.size()) {
                for (int j = 0; j < panelListUser.getComponents().length; j++) {
                    UserPanel userPanel = (UserPanel) panelListUser.getComponent(j);
                    if (userPanel.isRemove) {
                        panelListUser.remove(j);
                    }
                }
            }
        }
        if (isEdited){
            for (int j = 0; j < panelListUser.getComponents().length; j++) {
                UserPanel userPanel = (UserPanel) panelListUser.getComponent(j);
                userPanel.reload();
            }
            isEdited = false;
        }
        updateView();
    }

    /**
     * init other components
     */
    private void initOtherComponents() {
        try {
            ArrayList<UserDataObject> allUser = UserDataManagement.getAllUserByUserType(UserDataObject.USER_TYPE_ALL);

            for (int i = 0; i < allUser.size(); i++) {
                UserDataObject user = allUser.get(i);
                UserPanel userPanel = new UserPanel(user);
                userPanel.setVisible(true);
                panelListUser.add(userPanel);
            }
            updateView();
        } catch (Exception e) {
            System.out.println("Problem in loading init browse user form");
        }
    }

    private void updateView() {
        panelListUser.invalidate();
        panelListUser.updateUI();
    }
}
