/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocationPanel.java
 *
 * Created on Dec 5, 2010, 5:14:42 PM
 */
package com.localization.application.panel.item;

import com.localization.application.CaliratePanel;
import com.localization.manager.LocationDataManagement;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class LocationPanel extends javax.swing.JPanel {
 private CaliratePanel parent;

    /** Creates new form LocationPanel */
    public LocationPanel() {
        initComponents();
    }

    public LocationPanel(LocationDataObject location, CaliratePanel parent) {
        initComponents();
        this.location = location;
        this.parent = parent;
        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLocationName = new javax.swing.JLabel();
        buttonRemove = new javax.swing.JButton();

        labelLocationName.setText("Location Name"); // NOI18N

        buttonRemove.setText("remove"); // NOI18N
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelLocationName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(buttonRemove)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocationName)
                    .addComponent(buttonRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        this.isRemove = true;
        this.parent.removeLocation(location);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel labelLocationName;
    // End of variables declaration//GEN-END:variables
    private LocationDataObject location;
    public boolean isRemove = false;

    private void initOtherComponents() {
        this.labelLocationName.setText(location.getLocationName());
    }

    public String getLocationID() {
        return this.location.getLocationId();
    }
}
