/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectAlgorithmPanel.java
 *
 * Created on Jan 22, 2011, 10:10:35 AM
 */
package com.localization.application.panel.forframe;

import com.localization.application.panel.item.LocationPanel;
import com.localization.manager.AlgorithmDataManagement;
import com.localization.manager.LocationDataManagement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JPanel;
import localization.data.entity.contentobject.AlgorithmDataObject;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class AddAlgorithmPanel extends javax.swing.JPanel {

    private final LocationBrowseAlgorithm parentPanel;
    private final JDialog parentDialog;
    private final LocationDataObject location;

    /** Creates new form SelectAlgorithmPanel */
    public AddAlgorithmPanel() {
        this.parentDialog = null;
        this.parentPanel = null;
        this.location = null;
        initComponents();
    }

    public AddAlgorithmPanel(JDialog dialog, LocationBrowseAlgorithm aThis, LocationDataObject location) {
        this.parentDialog = dialog;
        this.parentPanel = aThis;
        this.location = location;
        initComponents();

        initOtherComponenets();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxForAlgorithm = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelLocationName = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        comboBoxForAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Select Algorithm");

        jLabel2.setText("Choose Algorithm");

        jLabel3.setText("LocationName");

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLocationName, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(comboBoxForAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(buttonOk)
                .addGap(66, 66, 66)
                .addComponent(buttonCancel)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxForAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk)
                    .addComponent(buttonCancel))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        if (!this.location.getAlgorithms().contains(this.comboBoxForAlgorithm.getSelectedItem())){
            this.location.addAlgorithm(((AlgorithmDataObject) this.comboBoxForAlgorithm.getSelectedItem()));
            //LocationDataManagement.updateLocation(location);
            LocationBrowseAlgorithm.isEdited = true;
            parentPanel.reload();
        }
        this.parentDialog.dispose();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.parentDialog.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox comboBoxForAlgorithm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelLocationName;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponenets() {
        this.labelLocationName.setText(this.location.getLocationName());
        ArrayList<AlgorithmDataObject> allAlgorithm = AlgorithmDataManagement.getAllAlgorithm();
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(allAlgorithm.toArray());
        comboBoxForAlgorithm.setModel(defaultComboBoxModel);
//        comboBoxForAlgorithm.get
        this.comboBoxForAlgorithm.updateUI();
        this.comboBoxForAlgorithm.invalidate();
        this.updateView();

    }

    /**
     * update view
     */
    public void updateView() {
        this.invalidate();
        this.updateUI();
    }
}
