/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateLocationPanel.java
 *
 * Created on Dec 4, 2010, 11:26:31 PM
 */
package com.localization.application.panel.forframe;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.application.panel.LocalizationPanel;
import com.localization.manager.AlgorithmDataManagement;
import com.localization.manager.LocationDataManagement;
import com.localization.manager.PointDataManagement;
import com.localization.other.PointValidator;
import localization.data.entity.contentobject.LocationDataObject;
import localization.data.entity.contentobject.PointDataObject;

import javax.swing.*;
import java.util.ArrayList;
import localization.data.entity.contentobject.AlgorithmDataObject;

/**
 *
 * @author leobin
 */
public class CreateLocationPanelWithSize extends LocalizationPanel {

    private JDialog parentDialog;
    private JPanel parentPanel;

    public CreateLocationPanelWithSize(JDialog dialog) {
        this.parentDialog = dialog;
        initComponents();

        initOtherComponents();
    }

    public CreateLocationPanelWithSize(JDialog dialog, JPanel panelMain) {
        initComponents();
        initOtherComponents();
        this.parentDialog = dialog;
        this.parentPanel = panelMain;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textLocationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textLocationHeight = new javax.swing.JTextField();
        textLocationWidth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        inputAlgorithm = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        jLabel1.setText("Create Root Location"); // NOI18N

        jLabel2.setText("Location Name"); // NOI18N

        textDescription.setColumns(20);
        textDescription.setRows(5);
        jScrollPane1.setViewportView(textDescription);

        jLabel3.setText("Location Description"); // NOI18N

        jLabel4.setText("jLabel4");

        jLabel5.setText("Algorithm");

        jLabel6.setText("Width");

        jLabel7.setText("pixels");

        jLabel8.setText("pixels");

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        inputAlgorithm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Height");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textLocationHeight, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textLocationWidth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)))
                            .addComponent(jScrollPane1)
                            .addComponent(textLocationName, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                            .addComponent(inputAlgorithm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(buttonCreate)
                .addGap(31, 31, 31)
                .addComponent(buttonCancel)
                .addGap(179, 179, 179))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textLocationWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLocationHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreate)
                    .addComponent(buttonCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        //create new root map and then add it to database
        String name = textLocationName.getText();
        String description = textDescription.getText();
        int width = Integer.parseInt(textLocationWidth.getText());
        int height = Integer.parseInt(textLocationHeight.getText());

        //create new location
        LocationDataObject location = new LocationDataObject();
        location.setLocationName(name);
        location.setLocationDescription(description);
        location.setContentZoom(1);
        location.setLocationId(LocationDataManagement.addNewLocation(location));

        location.setAlgorithm(((AlgorithmDataObject) inputAlgorithm.getSelectedItem()));
        
        location.setUser(LocalizationMain.loginUser);



        ArrayList<PointDataObject> listPoint = new ArrayList<PointDataObject>();
        //add list point to location
        PointDataObject point = PointValidator.createNewPoint(0, 0, 1);
        listPoint.add(point);
        point = PointValidator.createNewPoint(0, height, 2);
        listPoint.add(point);
        point = PointValidator.createNewPoint(width, height, 3);
        listPoint.add(point);
        point = PointValidator.createNewPoint(width, 0, 4);
        listPoint.add(point);
        PointDataManagement.addListPointToLocation(listPoint, location);


        this.parentDialog.dispose();
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_LOCATION);
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.parentDialog.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox inputAlgorithm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textLocationHeight;
    private javax.swing.JTextField textLocationName;
    private javax.swing.JTextField textLocationWidth;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reload() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private void initOtherComponents() {
        //create list algorithm
        ArrayList<AlgorithmDataObject> allAlgorithm = AlgorithmDataManagement.getAllAlgorithm();
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(allAlgorithm.toArray());
        inputAlgorithm.setModel(defaultComboBoxModel);
        this.updateView();
    }

    /**
     * update view
     */
    public void updateView() {
        this.updateUI();
        this.invalidate();
    }
}
