/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateLocationPanel.java
 *
 * Created on Dec 4, 2010, 11:26:31 PM
 */
package com.localization.application.panel.forframe;

import com.localization.application.LocalizationMain;
import com.localization.application.panel.LocalizationPanel;
import com.localization.application.panel.LocationManagementPanel;
import com.localization.manager.AlgorithmDataManagement;
import com.localization.manager.LocationDataManagement;
import com.localization.manager.PointDataManagement;
import com.localization.other.PointValidator;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JPanel;
import localization.data.entity.contentobject.AlgorithmDataObject;
import localization.data.entity.contentobject.LocationDataObject;
import localization.data.entity.contentobject.PointDataObject;

/**
 *
 * @author leobin
 */
public class CreateLocationPanel extends LocalizationPanel {

    private final JDialog parentDialog;
    private final JPanel parentPanelMain;
    private final ArrayList<Point> listPoints;

    /** Creates new form CreateLocationPanel */
    public CreateLocationPanel(JDialog dialog, JPanel panelMain, ArrayList<Point> listPoints) {
        this.parentDialog = dialog;
        this.parentPanelMain = panelMain;
        this.listPoints = listPoints;

        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputLocationName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputLocationDescription = new javax.swing.JScrollPane();
        textDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        jLabel1.setText("Create Location"); // NOI18N

        jLabel2.setText("Location Name"); // NOI18N

        textDescription.setColumns(20);
        textDescription.setRows(5);
        inputLocationDescription.setViewportView(textDescription);

        jLabel3.setText("Location Description"); // NOI18N

        jLabel4.setText("jLabel4");

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputLocationDescription)
                            .addComponent(inputLocationName, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(buttonCreate)
                        .addGap(66, 66, 66)
                        .addComponent(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputLocationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(inputLocationDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreate)
                    .addComponent(buttonCancel))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.closeDialog();
    }//GEN-LAST:event_buttonCancelActionPerformed

    private void closeDialog() {
        LocationManagementPanel.listNewPoints = new ArrayList<Point>();
        ((LocationManagementPanel) this.parentPanelMain).reloadAllView();
        this.parentDialog.dispose();
    }

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        // TODO add your handling code here:
        String name = inputLocationName.getText();
        String description = textDescription.getText();

        LocationDataObject location = new LocationDataObject();
        location.setLocationName(name);
        location.setLocationDescription(description);
        location.setContentZoom(LocationManagementPanel.zoomValue);
        location.setLocationId(LocationDataManagement.addNewLocation(location));

        location.setUser(LocalizationMain.loginUser);



        ArrayList<PointDataObject> listPoint = new ArrayList<PointDataObject>();

        for (int i = 0; i < this.listPoints.size(); i++) {
            Point point = this.listPoints.get(i);
            PointDataObject pointObject = PointValidator.createNewPoint(point.x, point.y, i + 1);
            listPoint.add(pointObject);
        }
        PointDataManagement.addListPointToLocation(listPoint, location);

        location.setParentLocation(LocationManagementPanel.rootLocation);

        LocationManagementPanel.rootLocation.addLocation(location);

        this.closeDialog();
    }//GEN-LAST:event_buttonCreateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JScrollPane inputLocationDescription;
    private javax.swing.JTextField inputLocationName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea textDescription;
    // End of variables declaration//GEN-END:variables

    @Override
    public void reload() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    private void initOtherComponents() {
    }

    /**
     * update view
     */
    public void updateView() {
        this.invalidate();
        this.updateUI();
    }
}
