/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateDataTypePanel.java
 *
 * Created on Feb 17, 2011, 11:06:19 AM
 */
package com.localization.application.panel.forframe;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.manager.DataTypeDataManagement;
import com.localization.other.ApplicationConfiguration;
import com.localization.other.PackageReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import localization.data.entity.contentobject.DataTypeDataObject;

/**
 *
 * @author leobint
 */
public class CreateDataTypePanel extends javax.swing.JPanel {

    private JDialog parent;
    private DataTypeDataObject datatype;
    private boolean isEdit = false;

    /** Creates new form CreateDataTypePanel */
    public CreateDataTypePanel(JDialog parent, DataTypeDataObject datatype) {
        this.parent = parent;
        this.datatype = datatype;
        initComponents();
        try {
            initOtherComponents();
        } catch (IOException ex) {
            Logger.getLogger(CreateDataTypePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateDataTypePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDescription = new javax.swing.JTextArea();
        inputClass = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonCreate = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        inputDescription.setColumns(20);
        inputDescription.setRows(5);
        jScrollPane1.setViewportView(inputDescription);

        inputClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Name");

        jLabel2.setText("Description");

        jLabel3.setText("Class");

        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(inputClass, 0, 267, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inputClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreate)
                    .addComponent(buttonCancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
        if (this.isEdit) {
            datatype.setDataTypeName(inputName.getText());
            datatype.setDataTypeDescription(inputDescription.getText());
            datatype.setDataTypeClassName((String) inputClass.getSelectedItem());
            DataTypeDataManagement.updateDataType(datatype);
        } else {
            datatype = new DataTypeDataObject();
            datatype.setDataTypeName(inputName.getText());
            datatype.setDataTypeDescription(inputDescription.getText());
            datatype.setDataTypeClassName((String) inputClass.getSelectedItem());
            datatype.setDataTypeId(DataTypeDataManagement.addNewDataType(datatype));
        }
        this.parent.dispose();
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_DATATYPE);
    }//GEN-LAST:event_buttonCreateActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.parent.dispose();
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_DATATYPE);
    }//GEN-LAST:event_buttonCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonCreate;
    private javax.swing.JComboBox inputClass;
    private javax.swing.JTextArea inputDescription;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponents() throws IOException, ClassNotFoundException {
        //init list datatype class
//        Class[] className = PackageReader.getclassName("com.localization.other");
        String[] className = PackageReader.getClassName(ApplicationConfiguration.load().datatypePackage);
        DefaultComboBoxModel defaultComboBoxModel = new DefaultComboBoxModel(className);
        inputClass.setModel(defaultComboBoxModel);

        if (this.datatype != null) {
            inputName.setText(datatype.getDataTypeName());
            inputDescription.setText(datatype.getDataTypeDescription());

            //init selected class for datatype
            int selectedClassIndex = 0;
            String selectedClassName = datatype.getDataTypeClassName();
            while (selectedClassIndex < className.length) {
                if (selectedClassName.equals(className[selectedClassIndex])) {
                    break;
                }
                selectedClassIndex++;
            }
            if (selectedClassIndex < className.length) {
                inputClass.setSelectedIndex(selectedClassIndex);
            }

            this.isEdit = true;
            buttonCreate.setText("Edit");
        }
    }
}
