/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocationBrowseAlgorithm.java
 *
 * Created on Mar 5, 2011, 9:22:29 PM
 */
package com.localization.application.panel.forframe;

import com.localization.application.LocalizationMain;
import com.localization.application.panel.item.AlgorithmPanel;
import com.localization.application.panel.item.LocationAlgorithmPanel;
import java.util.ArrayList;
import javax.swing.JDialog;
import localization.data.entity.contentobject.AlgorithmDataObject;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class LocationBrowseAlgorithm extends javax.swing.JPanel {

    public static boolean isEdited;
    private LocationDataObject location;
    private JDialog parentDialog;

    /** Creates new form LocationBrowseAlgorithm */
    public LocationBrowseAlgorithm(LocationDataObject location) {
        this.location = location;

        initComponents();

        initOtherComponents();
    }

    public LocationBrowseAlgorithm(JDialog dialog, LocationDataObject location) {
        this.location = location;
        this.parentDialog = dialog;


        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListAlgorithm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();

        panelListAlgorithm.setLayout(new javax.swing.BoxLayout(panelListAlgorithm, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Manage Algorithm");

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
            .addComponent(panelListAlgorithm, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(panelListAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonClose))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JDialog dialog = new JDialog(LocalizationMain.localizationMain, true);
        AddAlgorithmPanel panel = new AddAlgorithmPanel(dialog, this, location);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        // TODO add your handling code here:
        this.parentDialog.dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelListAlgorithm;
    // End of variables declaration//GEN-END:variables

    public void reload() {
        ArrayList<AlgorithmDataObject> allAlgorithm = new ArrayList<AlgorithmDataObject>(location.getAlgorithms());
        System.out.println(panelListAlgorithm.getComponents().length);
        System.out.println(allAlgorithm.size());
        if (panelListAlgorithm.getComponents().length < allAlgorithm.size()) {
            for (int j = panelListAlgorithm.getComponents().length; j < allAlgorithm.size(); j++) {
                AlgorithmDataObject algorithm = allAlgorithm.get(j);
                LocationAlgorithmPanel algorithmPanel = new LocationAlgorithmPanel(algorithm, this,location);
                algorithmPanel.setVisible(true);
                panelListAlgorithm.add(algorithmPanel);
            }
        } else {
            if (panelListAlgorithm.getComponents().length > allAlgorithm.size()) {
                for (int j = 0; j < panelListAlgorithm.getComponents().length; j++) {
                    LocationAlgorithmPanel algorithmPanel = (LocationAlgorithmPanel) panelListAlgorithm.getComponent(j);
                    if (algorithmPanel.isRemove) {
                        panelListAlgorithm.remove(j);
                    }
                }
            }
        }

        if (isEdited) {
            for (int j = 0; j < panelListAlgorithm.getComponents().length; j++) {
                AlgorithmPanel AlgorithmPanel = (AlgorithmPanel) panelListAlgorithm.getComponent(j);
                AlgorithmPanel.reload();
            }
            isEdited = false;
        }
        updateView();
    }

    /**
     * init other components
     */
    private void initOtherComponents() {
        try {
            ArrayList<AlgorithmDataObject> allAlgorithm = new ArrayList<AlgorithmDataObject>(location.getAlgorithms());

            for (int i = 0; i < allAlgorithm.size(); i++) {
                AlgorithmDataObject algorithm = allAlgorithm.get(i);
                LocationAlgorithmPanel algorithmPanel = new LocationAlgorithmPanel(algorithm, this,location);
                algorithmPanel.setVisible(true);
                panelListAlgorithm.add(algorithmPanel);
            }
            updateView();
        } catch (Exception e) {
            System.out.println("Problem in loading init browse algorithm form");
        }
    }

    private void updateView() {
        panelListAlgorithm.invalidate();
        panelListAlgorithm.updateUI();
    }
}
