/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlgorithmPanel.java
 *
 * Created on Feb 10, 2011, 9:56:30 PM
 */
package com.localization.application.panel.item;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.application.panel.BrowseAlgorithmPanel;
import com.localization.application.panel.forframe.CreateAlgorithmPanel;
import com.localization.manager.AlgorithmDataManagement;
import javax.swing.JDialog;
import localization.data.entity.contentobject.AlgorithmDataObject;

/**
 *
 * @author leobint
 */
public class AlgorithmPanel extends javax.swing.JPanel {

    private AlgorithmDataObject algorithm;
    public boolean isRemove = false;
    private boolean isEdit = false;

    /** Creates new form AlgorithmPanel */
    public AlgorithmPanel(AlgorithmDataObject algorithm) {
        this.algorithm = algorithm;
        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlgorithm = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();

        labelAlgorithm.setText("Algorithm Name");

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAlgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit)
                    .addComponent(buttonRemove)
                    .addComponent(labelAlgorithm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        AlgorithmDataManagement.removeAlgorithm(algorithm.getAlgorithmId());
        this.isRemove = true;
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_ALGORITHM);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        this.isEdit = true;
        BrowseAlgorithmPanel.isEdited = true;
        // TODO add your handling code here:
        JDialog dialog = new JDialog(LocalizationMain.localizationMain, true);
        CreateAlgorithmPanel panel = new CreateAlgorithmPanel(dialog, algorithm);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel labelAlgorithm;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponents() {
        if (algorithm.getLocations().size() > 0) {
            buttonRemove.setEnabled(false);
        }
        labelAlgorithm.setText(algorithm.getAlgorithmName());
    }

    public void reload() {
        if (isEdit) {
            AlgorithmDataManagement.updateAlgorithm(algorithm);
            initOtherComponents();
            isEdit = false;
        }
    }
}
