/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataTypePanel.java
 *
 * Created on Feb 17, 2011, 9:02:34 AM
 */
package com.localization.application.panel.item;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.application.panel.BrowseDataTypePanel;
import com.localization.application.panel.forframe.CreateDataTypePanel;
import com.localization.manager.DataTypeDataManagement;
import javax.swing.JDialog;
import localization.data.entity.contentobject.DataTypeDataObject;

/**
 *
 * @author leobint
 */
public class DataTypePanel extends javax.swing.JPanel {

    private DataTypeDataObject datatype;
    public boolean isRemove;
    private boolean isEdit = false;

    /** Creates new form DataTypePanel */
    public DataTypePanel(DataTypeDataObject datatype) {
        this.datatype = datatype;
        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDataTypeName = new javax.swing.JLabel();
        buttonRemove = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();

        labelDataTypeName.setText("jLabel1");

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataTypeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataTypeName)
                    .addComponent(buttonRemove)
                    .addComponent(buttonEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
                this.isEdit = true;
        BrowseDataTypePanel.isEdited = true;
        // TODO add your handling code here:
        JDialog dialog = new JDialog(LocalizationMain.localizationMain, true);
        CreateDataTypePanel panel = new CreateDataTypePanel(dialog, datatype);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        DataTypeDataManagement.removeDataType(datatype.getDataTypeId());
        this.isRemove = true;
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_DATATYPE);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void initOtherComponents() {
        this.isRemove = false;
        if (datatype.getAlgorithms().size() > 0){
            buttonRemove.setEnabled(false);
        }
        labelDataTypeName.setText(datatype.getDataTypeName());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel labelDataTypeName;
    // End of variables declaration//GEN-END:variables

    public void reload() {
        if (isEdit) {
            DataTypeDataManagement.updateDataType(datatype);
            initOtherComponents();
            isEdit = false;
        }
    }
}
