/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlgorithmPanel.java
 *
 * Created on Feb 10, 2011, 9:56:30 PM
 */
package com.localization.application.panel.item;

import com.localization.application.LocalizationMain;
import com.localization.application.panel.BrowseAlgorithmPanel;
import com.localization.application.panel.forframe.CreateAlgorithmPanel;
import com.localization.application.panel.forframe.LocationBrowseAlgorithm;
import com.localization.manager.AlgorithmDataManagement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import localization.data.entity.contentobject.AlgorithmDataObject;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobint
 */
public class LocationAlgorithmPanel extends javax.swing.JPanel {

    private AlgorithmDataObject algorithm;
    public boolean isRemove = false;
    private boolean isEdit = false;
    private LocationDataObject location;
    private LocationBrowseAlgorithm parentPanel;

    /** Creates new form AlgorithmPanel */
    public LocationAlgorithmPanel(AlgorithmDataObject algorithm, LocationBrowseAlgorithm parentPanel, LocationDataObject location) {
        this.algorithm = algorithm;
        this.location = location;
        this.parentPanel = parentPanel;
        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAlgorithm = new javax.swing.JLabel();
        buttonRemove = new javax.swing.JButton();

        labelAlgorithm.setText("Algorithm Name");

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAlgorithm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRemove)
                    .addComponent(labelAlgorithm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        if (this.location.getAlgorithms().size() > 1) {
            location.getAlgorithms().remove(algorithm);
//            AlgorithmDataManagement.removeAlgorithm(algorithm);
            this.isRemove = true;
        } else {
            JOptionPane.showMessageDialog(null, "You need at least one algorithm for location", "Error", 1);
        }
        parentPanel.reload();
    }//GEN-LAST:event_buttonRemoveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel labelAlgorithm;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponents() {
        if (this.location.getAlgorithms().size() < 2) {
            buttonRemove.setEnabled(false);
        }
        labelAlgorithm.setText(algorithm.getAlgorithmName());
    }

    public void reload() {
        if (isEdit) {
            AlgorithmDataManagement.updateAlgorithm(algorithm);
            initOtherComponents();
            isEdit = false;
        }
    }
}
