/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LocationPanel.java
 *
 * Created on Dec 5, 2010, 5:14:42 PM
 */
package com.localization.application.panel.item;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.application.panel.forframe.CreateLocationPanel;
import com.localization.application.panel.LocationManagementPanel;
import com.localization.application.panel.forframe.LocationBrowseAlgorithm;
import com.localization.application.panel.forframe.SelectAlgorithmPanel;
import com.localization.manager.LocationDataManagement;
import javax.swing.JDialog;
import localization.data.entity.contentobject.LocationDataObject;

/**
 *
 * @author leobin
 */
public class LocationPanel extends javax.swing.JPanel {

    /** Creates new form LocationPanel */
    public LocationPanel() {
        initComponents();
    }

    public LocationPanel(LocationDataObject location) {
        initComponents();
        this.location = location;
        initOtherComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLocationName = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        labelLocationName.setText("Location Name"); // NOI18N

        buttonEdit.setText("Edit"); // NOI18N
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonRemove.setText("remove"); // NOI18N
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        jButton1.setText("Algorithm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelLocationName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRemove)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLocationName)
                    .addComponent(buttonRemove)
                    .addComponent(buttonEdit)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        LocationDataManagement.removeLocation(location.getLocationId());
        this.isRemove = true;
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_LOCATION);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        LocationManagementPanel.rootLocation = this.location;
        LocationManagementPanel.treeRootLocation = this.location;

        //new location need to reset view
        LocationManagementPanel.isNeedToResetView = true;
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_LOCATION_MANAGEMENT);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Create new dialog for edit configuration
        JDialog dialog = new JDialog(LocalizationMain.localizationMain, true);
        LocationBrowseAlgorithm panel = new LocationBrowseAlgorithm(dialog, this.location);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelLocationName;
    // End of variables declaration//GEN-END:variables
    private LocationDataObject location;
    public boolean isRemove = false;

    private void initOtherComponents() {
        this.labelLocationName.setText(location.getLocationName());
    }

    public String getLocationID() {
        return this.location.getLocationId();
    }
}
