/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserPanel.java
 *
 * Created on Feb 12, 2011, 2:12:00 PM
 */
package com.localization.application.panel.item;

import com.localization.application.CardLayoutHandlerFunction;
import com.localization.application.LocalizationMain;
import com.localization.application.panel.BrowseUserPanel;
import com.localization.application.panel.forframe.CreateUserPanel;
import com.localization.manager.UserDataManagement;
import javax.swing.JDialog;
import localization.data.entity.contentobject.UserDataObject;

/**
 *
 * @author leobint
 */
public class UserPanel extends javax.swing.JPanel {

    private UserDataObject user;
    private boolean isEdit;
    public boolean isRemove;

    /** Creates new form UserPanel */
    public UserPanel(UserDataObject user) {
        this.user = user;
        this.isRemove = false;

        initComponents();

        initOtherComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUserName = new javax.swing.JLabel();
        buttonRemove = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();

        labelUserName.setText("username");

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserName)
                    .addComponent(buttonRemove)
                    .addComponent(buttonEdit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        UserDataManagement.removeUser(user.getUserId());
        this.isRemove = true;
        CardLayoutHandlerFunction.changeCardView(LocalizationMain.PANEL_BROWSE_USER);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        this.isEdit = true;
        BrowseUserPanel.isEdited = true;
        
        JDialog dialog = new JDialog(LocalizationMain.localizationMain, true);
        CreateUserPanel panel = new CreateUserPanel(dialog, user);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_buttonEditActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JLabel labelUserName;
    // End of variables declaration//GEN-END:variables

    private void initOtherComponents() {
        labelUserName.setText(user.getUserName());
    }

    public void reload() {
        if (isEdit) {
            UserDataManagement.updateUser(user);
            initOtherComponents();
            isEdit = false;
        }
    }

}
